[PQ]
pq_db_path = /mnt/vendor/odm_ext/etc/tvconfig/pq/pq.db
pq_overscan_db_path = /mnt/vendor/odm_ext/etc/tvconfig/pq/overscan.db
pq_ssm_data_path = /mnt/vendor/param/pq/ssm_data
pq_ssm_data_handler_path = /mnt/vendor/param/pq/SSMHandler
pq_wb_path = /dev/block/cri_data
pq.BigSmallDb.en= disable
pq.AllPQModule.en = enable
pq.ParamCheckSource.en = disable
pq.tvhal.en = disable
#amvecm module config
pq.sharpness0.en = enable
pq.sharpness1.en = enable
pq.sharpnesspi.en = enable
pq.dnlp.en = disable
pq.cm2.en = enable
#pq.amvecm.basic.en flag used to control contrast brightness contrast saturation and hue
pq.amvecm.basic.en = enable
pq.contrast.rgb.en = disable
pq.amvecm.basic.withOSD.en = disable
pq.contrast.rgb.withOSD.en = disable
pq.whitebalance.en = disable
pq.gamma.en = disable
pq.LocalContrast.en = disable
pq.BlackExtension.en = disable
pq.chroma.cor.en = disable
pq.xvycc.en = disable
pq.SuperResolution.en = enable
#di module config
pq.di.en = enable
pq.mcdi.en = enable
pq.deblock.en = enable
pq.NoiseReduction.en = disable
pq.DemoSquito.en = enable
#overscan config
pq.DisplayOverscan.en = disable
# new picture mode
pq.new_picture_mode.en = enable
#aisr
pq.aisr.en = enable
#aipq
pq.ai.en = enable
#pq param default value(all these def value is according to the enum in code)
pq.PictureMode.def = 0
pq.ColorTemperature.def = 0
pq.ColorDemoMode.def = 0
pq.ColorBaseMode.def = 1
pq.ColorSpace.def = 0
pq.RGBGainR.def = 1024
pq.RGBGainG.def = 1024
pq.RGBGainB.def = 1024
pq.RGBPostOffsetR.def = 0
pq.RGBPostOffsetG.def = 0
pq.RGBPostOffsetB.def = 0
pq.GammaLevel.def = 0
pq.DisplayMode.def = 0
pq.AutoAspect.def = 1
pq.43Stretch.def = 0
pq.DnlpLevel.def = 2
pq.DnlpGain.def = 0
pq.EyeProtectionMode.def = 0
pq.DDRSSC.def = 0
pq.LVDSSSC.def = 0, 0
pq.LocalContrastMode.def = 2
pq.DeblockMode.def = 2
pq.DemoSquitoMode.def = 2
pq.AisrMode.def = 3
pq.AipqMode.def = 2

[BACKLIGHT]
auto.backlight.thtf = 8
auto.backlight.lutmode = 1
auto.backlight.lutvalue_high = 25,170,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255
auto.backlight.lutvalue_low = 102,217,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255

[HDMI]
#edid version: edid_14 or edid_20
hdmi.edid.version.def = edid_14
hdmi.hdcp.switcher.def = 0
#colorrange mode: auto or full or limit
hdmi.color.range.mode.def = auto
hdmi.out.with.fbc.en = disable

[AUTO_NR]
auto.nr.motion_th = 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
auto.nr.motion_lp_ygain = 32,7,6,7,7,8,12,23,46,62,62,63,63,63,63,64
auto.nr.motion_hp_ygain = 32,8,8,9,9,8,11,23,47,62,62,62,63,63,63,64
auto.nr.motion_lp_cgain = 32,32,31,32,31,30,29,46,64,64,64,64,64,64,64,64
auto.nr.motion_hp_cgain = 64,64,64,64,64,64,64,64,64,64,64,64,64,64,64,64
auto.nr.apl_gain = 32,16,10,8,6,5,4,4
