[AM_AUDIO_COMMON]
ini_key_am_audio_common_driver_base_project = 0

[AM_AUDIO_MANAGER]
ini_key_am_audio_manager_coexist_spdif_other = 1
db_key_am_audio_config_audio_soundbar_mode_enable = 0
# 0:OFF 1:Line 2:RF
db_key_am_audio_config_dolby_audio_drc_mode = 2
# 0:PCM 1:Auto 2:MANUAL 3:PASSTHROUGH 4:ALWAYS
db_key_am_audio_config_digital_audio_mode = 1
db_key_am_audio_config_sound_spdif_output_enable = 1
db_key_am_audio_config_sound_speaker_output_enable = 1
db_key_am_audio_config_audio_dialogue_enhancement_switch = 0
# 0:SURROUND 1:stereo
db_key_am_audio_config_sound_dmx_mode = 0
db_key_am_audio_config_force_ddp_switch = 0
db_key_am_audio_config_dolby_audio_drc_level = 100
# 0:0ms
db_key_am_audio_config_audio_output_speaker_delay_atv = 0
db_key_am_audio_config_audio_output_speaker_delay_dtv = 0
db_key_am_audio_config_audio_output_speaker_delay_av = 0
db_key_am_audio_config_audio_output_speaker_delay_hdmi = 0
db_key_am_audio_config_audio_output_speaker_delay_media = 0
db_key_am_audio_config_audio_output_spdif_delay_atv = 0
db_key_am_audio_config_audio_output_spdif_delay_dtv = 0
db_key_am_audio_config_audio_output_spdif_delay_av = 0
db_key_am_audio_config_audio_output_spdif_delay_hdmi = 0
db_key_am_audio_config_audio_output_spdif_delay_media = 0
db_key_am_audio_config_audio_output_headphone_delay_atv = 0
db_key_am_audio_config_audio_output_headphone_delay_dtv = 0
db_key_am_audio_config_audio_output_headphone_delay_av = 0
db_key_am_audio_config_audio_output_headphone_delay_hdmi = 0
db_key_am_audio_config_audio_output_headphone_delay_media = 0
db_key_am_audio_config_audio_output_all_delay = 0
db_key_am_audio_config_dts_x_audio_drc_mode = 1
# 0:ATV 1:DTV 2:AV 3:HDMI 4:MEDIA
db_key_am_audio_config_tv_source_type = 4
#AIDE
db_key_am_audio_config_aide_enable = 0
db_key_am_audio_config_aide_gain = 0
# 0:BUILT_IN 1:LINE_IN 2:USB_IN
db_key_am_audio_config_sound_mic_source = 2
db_key_am_audio_config_sound_global_linein_mic_enable = 0
db_key_am_audio_config_sound_linein_mic_mute = 0
db_key_am_audio_config_sound_linein_mic_gain = 10
db_key_am_audio_config_sound_linein_mic_reverb = 0
db_key_am_audio_config_sound_linein_mic_reverb_level = 0
db_key_am_audio_config_global_usb_mic_enable = 0
db_key_am_audio_config_usb_mic_mute = 0
db_key_am_audio_config_usb_mic_gain = 10
db_key_am_audio_config_usb_mic_reverb = 0
db_key_am_audio_config_usb_mic_reverb_level = 0


[AM_AUDIO_EFFECT]
# 0 - 100
db_key_am_audio_effect_balance = 50
db_key_am_audio_effect_treblebass_bass = 50
db_key_am_audio_effect_treblebass_treble = 50

# 1: DAP2.4, 0: DAP1.3.2
ini_key_am_audio_effect_dap_version = 1
db_key_am_audio_effect_dap_mode = -1
db_key_am_audio_effect_dap_geq = 1
db_key_am_audio_effect_dap_post_gain = 0
db_key_am_audio_effect_dap_vl = 1
db_key_am_audio_effect_dap_vl_amount = 0
db_key_am_audio_effect_dap_de = 0
db_key_am_audio_effect_dap_de_amount = 0
db_key_am_audio_effect_dap_surround = 0
db_key_am_audio_effect_dap_surround_boost = 0
db_key_am_audio_effect_dap_geq_band1 = 0
db_key_am_audio_effect_dap_geq_band2 = 0
db_key_am_audio_effect_dap_geq_band3 = 0
db_key_am_audio_effect_dap_geq_band4 = 0
db_key_am_audio_effect_dap_geq_band5 = 0
db_key_am_audio_effect_dap_2_4_profile = -1
db_key_am_audio_effect_dap_2_4_surround_virtualizer_mode = 0
db_key_am_audio_effect_dap_2_4_surround_virtualizer_boost = 96
db_key_am_audio_effect_dap_2_4_dialogue_enhancer_enable = 0
db_key_am_audio_effect_dap_2_4_bass_enhancer_enable = 0
db_key_am_audio_effect_dap_2_4_bass_enhancer_boost = 192
db_key_am_audio_effect_dap_2_4_bass_enhancer_cutoffX100 = 2
db_key_am_audio_effect_dap_2_4_bass_enhancer_cutoffX1 = 0
db_key_am_audio_effect_dap_2_4_bass_enhancer_width = 16
db_key_am_audio_effect_dap_2_4_mi_steering = 0
db_key_am_audio_effect_dap_2_4_surround_decoder_enable = 1
db_key_am_audio_effect_dap_2_4_leveler_mode = 0
db_key_am_audio_effect_dap_2_4_leveler_strength = 4

db_key_am_audio_effect_dpe_enabled = 0
db_key_am_audio_effect_dpe_inputgain = 0
db_key_am_audio_effect_dpe_pre_eq = 0
db_key_am_audio_effect_dpe_pre_eq_band0 = 0
db_key_am_audio_effect_dpe_pre_eq_band0_cutofffrequency = 3000
db_key_am_audio_effect_dpe_pre_eq_band0_gain = 0
db_key_am_audio_effect_dpe_pre_eq_band1 = 0
db_key_am_audio_effect_dpe_pre_eq_band1_cutofffrequency = 6000
db_key_am_audio_effect_dpe_pre_eq_band1_gain = 0
db_key_am_audio_effect_dpe_pre_eq_band2 = 0
db_key_am_audio_effect_dpe_pre_eq_band2_cutofffrequency = 9000
db_key_am_audio_effect_dpe_pre_eq_band2_gain = 0
db_key_am_audio_effect_dpe_mbc = 0
db_key_am_audio_effect_dpe_mbc_band0 = 0
db_key_am_audio_effect_dpe_mbc_band0_cutoffFrequency = 3000
db_key_am_audio_effect_dpe_mbc_band0_attacktime = 150
db_key_am_audio_effect_dpe_mbc_band0_releasetime = 320
db_key_am_audio_effect_dpe_mbc_band0_ratio = 1
db_key_am_audio_effect_dpe_mbc_band0_threshold = -10
db_key_am_audio_effect_dpe_mbc_band0_kneewidth = 0
db_key_am_audio_effect_dpe_mbc_band0_noisegate_threshold = -80
db_key_am_audio_effect_dpe_mbc_band0_expander_ratio = 1
db_key_am_audio_effect_dpe_mbc_band0_pre_gain = 0
db_key_am_audio_effect_dpe_mbc_band0_post_gain = 0
db_key_am_audio_effect_dpe_mbc_band1 = 0
db_key_am_audio_effect_dpe_mbc_band1_cutoffFrequency = 6000
db_key_am_audio_effect_dpe_mbc_band1_attacktime = 150
db_key_am_audio_effect_dpe_mbc_band1_releasetime = 320
db_key_am_audio_effect_dpe_mbc_band1_ratio = 1
db_key_am_audio_effect_dpe_mbc_band1_threshold = -10
db_key_am_audio_effect_dpe_mbc_band1_kneewidth = 0
db_key_am_audio_effect_dpe_mbc_band1_noisegate_threshold = -80
db_key_am_audio_effect_dpe_mbc_band1_expander_ratio = 1
db_key_am_audio_effect_dpe_mbc_band1_pre_gain = 0
db_key_am_audio_effect_dpe_mbc_band1_post_gain = 0
db_key_am_audio_effect_dpe_mbc_band2 = 0
db_key_am_audio_effect_dpe_mbc_band2_cutoffFrequency = 9000
db_key_am_audio_effect_dpe_mbc_band2_attacktime = 150
db_key_am_audio_effect_dpe_mbc_band2_releasetime = 320
db_key_am_audio_effect_dpe_mbc_band2_ratio = 1
db_key_am_audio_effect_dpe_mbc_band2_threshold = -10
db_key_am_audio_effect_dpe_mbc_band2_kneewidth = 0
db_key_am_audio_effect_dpe_mbc_band2_noisegate_threshold = -80
db_key_am_audio_effect_dpe_mbc_band2_expander_ratio = 1
db_key_am_audio_effect_dpe_mbc_band2_pre_gain = 0
db_key_am_audio_effect_dpe_mbc_band2_post_gain = 0
db_key_am_audio_effect_dpe_post_eq = 0
db_key_am_audio_effect_dpe_post_eq_band0 = 0
db_key_am_audio_effect_dpe_post_eq_band0_cutofffrequency = 3000
db_key_am_audio_effect_dpe_post_eq_band0_gain = 0
db_key_am_audio_effect_dpe_post_eq_band1 = 0
db_key_am_audio_effect_dpe_post_eq_band1_cutofffrequency = 6000
db_key_am_audio_effect_dpe_post_eq_band1_gain = 0
db_key_am_audio_effect_dpe_post_eq_band2 = 0
db_key_am_audio_effect_dpe_post_eq_band2_cutofffrequency = 9000
db_key_am_audio_effect_dpe_post_eq_band2_gain = 0
db_key_am_audio_effect_dpe_limiter = 0
db_key_am_audio_effect_dpe_limiter_attacktime = 150
db_key_am_audio_effect_dpe_limiter_releasetime = 320
db_key_am_audio_effect_dpe_limiter_ratio = 30
db_key_am_audio_effect_dpe_limiter_threshold = -25
db_key_am_audio_effect_dpe_limiter_post_gain = 0

db_key_am_audio_effect_hpeq_sound_mode = 0
db_key_am_audio_effect_hpeq_band1 = 0
db_key_am_audio_effect_hpeq_band2 = 0
db_key_am_audio_effect_hpeq_band3 = 0
db_key_am_audio_effect_hpeq_band4 = 0
db_key_am_audio_effect_hpeq_band5 = 0
db_key_am_audio_effect_hpeq_band6 = 0
db_key_am_audio_effect_hpeq_band7 = 0
db_key_am_audio_effect_hpeq_band8 = 0
db_key_am_audio_effect_hpeq_band9 = 0

db_key_am_audio_effect_virtualsurround_enable = 0

# virtual X version 1
ini_key_am_audio_effect_virtualx_version = 1
db_key_am_audio_effect_virtualx_mode = 0
db_key_am_audio_effect_virtualx_truvolume_hd_enabled = 0
db_key_am_audio_effect_virtualx_dialog_clarity_mode = 0
db_key_am_audio_effect_virtualx_enabled = 0
db_key_am_audio_effect_virtualx_virtual_surround = 0
db_key_am_audio_effect_virtualx_trubass_discard = 0

db_key_am_audio_effect_dual_sound_effect_mode = 0
db_key_am_audio_effect_basic_effect_mode = 0

[AM_AUDIO_MPEGH]
db_key_am_audio_config_mpegh_persist = 0
mpegh_audio_lang = 0
mpegh_label_lang = 0
mpegh_drc_att = 0
mpegh_accessibility = 0
mpegh_drc_effect = 0
mpegh_drc_album = 0
mpegh_drc_boost = 0
mpegh_tl = 0

