# config model summer
[OHM]
AMLOGIC_SOC_INI_PATH  = /vendor/etc/audio_config/AMLOGIC_SOC_OHM.ini
AMLOGIC_AUDIO_EFFECT_INI_PATH  = /vendor/etc/audio_config/AUDIO_EFFECT_OHM.ini
EXT_AMP_INI_PATH  = /vendor/etc/audio_config/EXT_AMP_OHM.ini

[OHM_WV4]
AMLOGIC_SOC_INI_PATH  = /vendor/etc/audio_config/AMLOGIC_SOC_OHM_WV4.ini
AMLOGIC_AUDIO_EFFECT_INI_PATH  = /vendor/etc/audio_config/AUDIO_EFFECT_OHM_WV4.ini
EXT_AMP_INI_PATH  = /vendor/etc/audio_config/EXT_AMP_OHM_WV4.ini

[ROSS]
AMLOGIC_SOC_INI_PATH  = /vendor/etc/audio_config/AMLOGIC_SOC_ROSS.ini
AMLOGIC_AUDIO_EFFECT_INI_PATH  = /vendor/etc/audio_config/AUDIO_EFFECT_ROSS.ini
EXT_AMP_INI_PATH  = /vendor/etc/audio_config/EXT_AMP_ROSS.ini